CREATE TABLE users (
    user_id BIGINT NOT NULL PRIMARY KEY,
    wallet BIGINT NOT NULL DEFAULT 0,
    bank BIGINT NOT NULL DEFAULT 0,
    max_bank BIGINT NOT NULL DEFAULT 100,
    exp BIGINT NOT NULL DEFAULT 0
);