ALTER TABLE users
    ADD COLUMN IF NOT EXISTS job TEXT,
    ADD COLUMN IF NOT EXISTS job_salary BIGINT,
    ADD COLUMN IF NOT EXISTS job_cooldown_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS job_switch_cooldown_expires_at TIMESTAMP WITH TIME ZONE,
    ADD COLUMN IF NOT EXISTS job_hours INTEGER,
    ADD COLUMN IF NOT EXISTS work_experience INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS iq BIGINT NOT NULL DEFAULT 0;
