CREATE TABLE IF NOT EXISTS pets (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    pet TEXT NOT NULL,
    exp BIGINT NOT NULL DEFAULT 0,
    duplicates INTEGER NOT NULL DEFAULT 0,
    evolution INTEGER NOT NULL DEFAULT 0,
    last_recorded_energy BIGINT NOT NULL DEFAULT 0,
    last_feed TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    max_energy BIGINT NOT NULL DEFAULT 100,
    equipped BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id, pet)
);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS max_equipped_pets INTEGER NOT NULL DEFAULT 3;